### ISSUE TITLE
TODO: Fix End of Match behaviour

### ISSUE THREAD

**Issue by JustCodiex** [JustCodiex/coh2-battlegrounds#101]
- [x] On match failure, all participants are informed
- [x] The host cannot cancel when starting a match
- ~~[ ] Move gamemode upload to dedicated TCP channel.~~
- [x] Participants end of match button still says "Playing" after the game has closed...
- [x] Participants are not informed of host-side progress.
- [x] Verify Steam is running before launching
- [x] Verify CoH2 is *not* running while setting up.
- [x] Verify all participants have the gamemode installed before launching the game.

**Comment by JustCodiex** [comment]
- [ ] Participants are not informed of host-side progress.

**Comment by JustCodiex** [comment]
- [ ] Verify Steam is running before launching
