### ISSUE TITLE
TODO: Callbacks on view switching

### ISSUE THREAD

**Issue by JustCodiex** [JustCodiex/coh2-battlegrounds#102]
- [x] Notify views being switched away
- [x] Notify views being switched to
- [x] Allow editing companies directly from the lobby.
- [x] Ask the user to exit if in the lobby or save before exiting when in the company editor.
