### ISSUE TITLE
TODO: Ammunition System

### ISSUE THREAD

**Issue by JustCodiex** [JustCodiex/coh2-battlegrounds#109]
- [x] Primary Soviet Weapons
- [x] Primary Wehrmacht Weapons
- [x] Garrison UI support
- [x] Additional methods of supply (Soviet)
- [x] Additional methods of supply (Wehrmacht) (Ticked, see #188 )
- [x] Method of refuelling in the field

**Comment by JustCodiex** [comment]
Needs supply trucks

**Comment by JustCodiex** [comment]
Created branch, starting work on supply
