### ISSUE TITLE
TODO: Company Auto-Reinforce

### ISSUE THREAD

**Issue by JustCodiex** [JustCodiex/coh2-battlegrounds#152]
**Is your feature request related to a problem? Please describe.**
When a unit is lost it may be desired to keep the company composition.

**Describe the solution you'd like**
Allow companies to automatically reinforce lost units. That is, lost units are replaced with by fresh unit with the same settings.

** Todo **
- [x] Visual Toggle in Company Builder
- [x] Auto-Reinforce on lost units in match finaliser.

**Comment by JustCodiex** [comment]
- [ ] Visual Toggle in Company Builder
- [ ] Auto-Reinforce on lost units in match finaliser.
