### ISSUE TITLE
TODO: Company Items

### ISSUE THREAD

**Issue by JustCodiex** [JustCodiex/coh2-battlegrounds#160]
- [x] Detect capture of units ingame
- [x] Report captured items
- [x] Preserve capturing units if possible (ie when a squad splits to crew a TW it's not lost)
- [x] Show captured items in company
- [x] Let people add captured units to their company as active units.
