### ISSUE TITLE
TODO: GUI enhancements

### ISSUE THREAD

**Issue by RagnarTheEverchosen** [JustCodiex/coh2-battlegrounds#199]
**Company Browser**
- [x] Add company type icon next to their name.
- [x] Add faction icon next to to their name.
- [x] Make faction names capitalise first letter.
- [x] Company Type Descriptions when creating a new company.

**Lobby**
- [x] 20 Min Min
- [x] Planning view is not destroyed after leaving.

**Comment by JustCodiex** [comment]
Whoop
